return {
	BlinkCmpMenu = { ctermfg = 250 },
	BlinkCmpKind = { link = "BlinkCmpMenu" },
	BlinkCmpMenuBorder = { link = "FloatBorder" },
	BlinkCmpMenuSelection = { link = "CursorLine" },
	BlinkDocBorder = { link = "FloatBorder" },
	BlinkDocSeparator = { link = "FloatBorder" },
	BlinkDoc = { link = "NormalFloat" },
	BlinkCmpDocBorder = { link = "FloatBorder" },
	BlinkCmpDocSeparator = { link = "FloatBorder" },
	BlinkCmpDoc = { link = "NormalFloat" },

	BlinkCmpKindOperator = { link = "Operator" },
	BlinkCmpKindConstant = { link = "Constant" },
	BlinkCmpKindEnumMember = { link = "Constant" },
	BlinkCmpKindSnippet = { link = "Constant" },
	BlinkCmpKindVariable = { link = "Normal" },
	BlinkCmpKindMethod = { link = "Method" },
	BlinkCmpKindFunction = { link = "Function" },
	BlinkCmpKindKeyword = { link = "Keyword" },
	BlinkCmpKindModule = { link = "Keyword" },
	BlinkCmpKindUnit = { link = "Keyword" },
	BlinkCmpKindEnum = { link = "Type" },
	BlinkCmpKindClass = { link = "Type" },
	BlinkCmpKindInterface = { link = "Type" },
	BlinkCmpKindStruct = { link = "Type" },
	BlinkCmpKindText = { link = "String" },
	BlinkCmpKindFile = { link = "Normal" },
	BlinkCmpKindFolder = { link = "Directory" },
	BlinkCmpKindProperty = { link = "Property" },
	BlinkCmpKindField = { link = "Property" },
	BlinkCmpKindValue = { link = "Property" },
}
