return {
	CmpBorder = { link = "FloatBorder" },
	CmpNormal = { ctermfg = 250 },
	CmpCursorLine = { link = "CursorLine" },

	CmpDocumentationBorder = { link = "FloatBorder" },
	CmpDocumentationNormal = { link = "Normal" },
	CmpDocumentationCursorLine = { link = "CursorLine" },

	CmpItemAbbrDeprecated = { link = "Comment" },
	CmpItemAbbrMatch = { ctermfg = 1 },

	CmpItemKindConstant = { link = "Constant" },
	CmpItemKindEnumMember = { link = "Constant" },
	CmpItemKindSnippet = { link = "Constant" },
	CmpItemKindVariable = { ctermfg = 7 },
	CmpItemKindMethod = { link = "Method" },
	CmpItemKindFunction = { link = "Function" },
	CmpItemKindKeyword = { link = "Keyword" },
	CmpItemKindModule = { link = "Keyword" },
	CmpItemKindUnit = { link = "Keyword" },
	CmpItemKindEnum = { link = "Type" },
	CmpItemKindClass = { link = "Type" },
	CmpItemKindInterface = { link = "Type" },
	CmpItemKindStruct = { link = "Type" },
	CmpItemKindText = { link = "String" },
	CmpItemKindFile = { ctermfg = 7 },
	CmpItemKindFolder = { link = "Directory" },
	CmpItemKindProperty = { link = "Property" },
	CmpItemKindField = { link = "Property" },
	CmpItemKindValue = { link = "Property" },

	CmpItemKindConstantIcon = { link = "CmpItemKindConstant" },
	CmpItemKindEnumMemberIcon = { link = "CmpItemKindEnumMember" },
	CmpItemKindSnippetIcon = { link = "CmpItemKindSnippet" },
	CmpItemKindVariableIcon = { link = "CmpItemKindVariable" },
	CmpItemKindMethodIcon = { link = "CmpItemKindMethod" },
	CmpItemKindFunctionIcon = { link = "CmpItemKindFunction" },
	CmpItemKindKeywordIcon = { link = "CmpItemKindKeyword" },
	CmpItemKindModuleIcon = { link = "CmpItemKindModule" },
	CmpItemKindUnitIcon = { link = "CmpItemKindUnit" },
	CmpItemKindEnumIcon = { link = "CmpItemKindEnum" },
	CmpItemKindClassIcon = { link = "CmpItemKindClass" },
	CmpItemKindInterfaceIcon = { link = "CmpItemKindInterface" },
	CmpItemKindStructIcon = { link = "CmpItemKindStruct" },
	CmpItemKindTextIcon = { link = "CmpItemKindText" },
	CmpItemKindFileIcon = { link = "CmpItemKindFile" },
	CmpItemKindFolderIcon = { link = "CmpItemKindFolder" },
	CmpItemKindPropertyIcon = { link = "CmpItemKindProperty" },
	CmpItemKindFieldIcon = { link = "CmpItemKindField" },
	CmpItemKindValueIcon = { link = "CmpItemKindValue" },
}
