return {
	Normal = { ctermfg = 7 },
	NormalFloat = { ctermfg = 7 },
	FloatBorder = { ctermfg = 240 },
	WinSeparator = { ctermfg = 0 },
	EndOfBuffer = { ctermfg = 16 },
	StatusLine = { ctermfg = 246 },
	StatusLineNC = { link = "StatusLine" },
	LineNr = { ctermfg = 237 },
	Visual = { ctermbg = 53 },
	LspInlayHint = { ctermbg = 233, ctermfg = 248 },
	Folded = { ctermbg = 1, ctermfg = 16 },
	Search = { ctermbg = 6, ctermfg = 16 },
	CurSearch = { ctermbg = 1, ctermfg = 16 },
	Pmenu = { ctermfg = 245, ctermbg = 233 },
	PmenuSel = { ctermfg = 16, ctermbg = 1, underline = false, bold = true },
	PmenuSbar = { ctermbg = 236 },
	PmenuThumb = { ctermbg = 240 },
	Directory = { ctermfg = 1, bold = true },

	netrwHelpCmd = { ctermfg = 6 },
	netrwClassify = { link = "Directory" },

	Comment = { ctermfg = 245, italic = true },
	Operator = { ctermfg = 1 },
	Builtin = { ctermfg = 1, bold = true },
	Property = { ctermfg = 99, nocombine = true },
	Keyword = { ctermfg = 5 },
	PerProc = { link = "Keyword" },
	Identifier = { link = "Keyword" },
	String = { ctermfg = 2, italic = true },
	Method = { ctermfg = 6 },
	Function = { ctermfg = 4 },
	Delimiter = { ctermfg = 246 },
	Statement = { link = "Delimiter" },
	Type = { ctermfg = 3 },
	Special = { link = "Type" },
	Constant = { ctermfg = 209 },

	DiagnosticUnnecessary = { ctermfg = 245 },
	DiagnosticHint = { ctermfg = 6 },
	DiagnosticError = { ctermfg = 1 },
	DiagnosticWarn = { ctermfg = 3 },
	DiagnosticInfo = { ctermfg = 2 },
}
