return {
	Title = { ctermfg = 0, ctermbg = 1 },
	SubNormal = { ctermbg = 16 },
	Normal = { ctermfg = 7, ctermbg = 233 },
	NormalFloat = { ctermbg = 235 },
	FloatBorder = { ctermfg = 235 },
	WinSeparator = { ctermfg = 240 },
	EndOfBuffer = { ctermfg = 233 },
	StatusLine = { ctermfg = 247, ctermbg = 232 },
	StatusLineNC = { link = "StatusLine" },
	LineNr = { ctermfg = 238 },
	Visual = { ctermbg = 53 },
	LspInlayHint = { ctermbg = 233, ctermfg = 248 },
	Folded = { ctermbg = 1, ctermfg = 16 },
	Search = { ctermbg = 6, ctermfg = 0 },
	CurSearch = { ctermbg = 1, ctermfg = 16 },
	Pmenu = { ctermfg = 245, ctermbg = 233 },
	PmenuSel = { ctermfg = 209, underline = false },
	PmenuSbar = { ctermbg = 236 },
	PmenuThumb = { ctermbg = 240 },
	CursorLine = { ctermbg = 234 },
	CursorLineNr = { ctermfg = 209, ctermbg = 233, bold = true },
	CursorLineSign = { ctermfg = 209, ctermbg = 233, bold = true },

	Directory = { ctermfg = 252 },
	File = { ctermfg = 250 },
	DotFile = { ctermfg = 244 },
	IndentMarker = { ctermfg = 237 },

	Added = { ctermfg = 2 },
	Untracked = { link = "Added" },
	Unstaged = { link = "Added" },
	Staged = { ctermfg = 220 },
	Deleted = { ctermfg = 1 },
	Modified = { ctermfg = 3 },
	Renamed = { link = "Modified" },
	Ignored = { link = "Comment" },

	DiffAdd = { ctermfg = 2, ctermbg = 22 },
	DiffChange = { ctermfg = 3, ctermbg = 58 },
	DiffDelete = { ctermfg = 1, ctermbg = 52 },
	diffOldFile = { ctermfg = 243, underline = true },
	diffNewFile = { ctermfg = 4, underline = true },
	diffFile = { link = "Title" },
	gitHash = { ctermfg = 248 },
	gitIdentityKeyword = { ctermfg = 254 },
	gitIdentity = { ctermfg = 7 },

	netrwHelpCmd = { ctermfg = 6 },
	netrwClassify = { link = "Directory" },

	Comment = { ctermfg = 242, italic = true },
	Operator = { ctermfg = 1 },
	Builtin = { ctermfg = 1, bold = true },
	Property = { ctermfg = 99, nocombine = true },
	Keyword = { ctermfg = 5 },
	PerProc = { link = "Keyword" },
	Identifier = { link = "Keyword" },
	String = { ctermfg = 2, italic = true },
	Method = { ctermfg = 6 },
	Function = { ctermfg = 4 },
	Delimiter = { ctermfg = 249 },
	Statement = { link = "Delimiter" },
	Type = { ctermfg = 3 },
	Special = { link = "Type" },
	Constant = { ctermfg = 209 },

	DiagnosticUnnecessary = { ctermfg = 245 },
	DiagnosticError = { ctermfg = 1 },
	DiagnosticWarn = { ctermfg = 3 },
	DiagnosticInfo = { ctermfg = 2 },
	DiagnosticHint = { ctermfg = 6 },
}
