return {
	NeoTreeDirectoryIcon = { link = "Directory" },
	NeoTreeDirectoryName = { link = "Directory" },
	NeoTreeRootName = { ctermfg = 1, bold = true, underline = true },
	NeoTreeIndentMarker = { link = "LineNr" },
	NeoTreeDimText = { link = "Comment" },
	NeoTreeMessage = { link = "Comment" },
	NeoTreeDotFile = { ctermfg = 160 },
	NeoTreeGitAdded = { ctermfg = 2 },
	NeoTreeGitUntracked = { link = "NeoTreeGitAdded" },
	NeoTreeGitStaged = { ctermfg = 220 },
	NeoTreeGitModified = { ctermfg = 3 },
	NeoTreeGitUnstaged = { ctermfg = 3, underline = true },
	NeoTreeGitDeleted = { ctermfg = 1, strikethrough = true },
	NeoTreeGitIgnored = { link = "Comment" },
	NeoTreeFloatNormal = { link = "NormalFloat" },
	NeoTreeFloatBorder = { link = "FloatBorder" },
	NeoTreeFloatTitle = { link = "Title" },
	NeoTreeTitleBar = { link = "Title" },
}
