local integracion_lsp = require("mestizo256.lsp.markdown")

return {
	MarkviewHeading1 = { link = "@markup.heading.1.markdown" },
	MarkviewHeading2 = { link = "@markup.heading.2.markdown" },
	MarkviewHeading3 = { link = "@markup.heading.3.markdown" },
	MarkviewHeading4 = { link = "@markup.heading.4.markdown" },
	MarkviewHeading5 = { link = "@markup.heading.5.markdown" },
	MarkviewHeading6 = { link = "@markup.heading.6.markdown" },
	MarkviewHeading1Sign = { ctermfg = integracion_lsp["@markup.heading.1.markdown"].ctermfg },
	MarkviewHeading2Sign = { ctermfg = integracion_lsp["@markup.heading.2.markdown"].ctermfg },
	MarkviewHeading3Sign = { ctermfg = integracion_lsp["@markup.heading.3.markdown"].ctermfg },
	MarkviewHeading4Sign = { ctermfg = integracion_lsp["@markup.heading.4.markdown"].ctermfg },
	MarkviewHeading5Sign = { ctermfg = integracion_lsp["@markup.heading.5.markdown"].ctermfg },
	MarkviewHeading6Sign = { ctermfg = integracion_lsp["@markup.heading.6.markdown"].ctermfg },
	MarkviewCode = { link = "@markup.raw.block.markdown" },
	MarkviewInlineCode = { link = "@markup.raw.block.markdown" },
	MarkviewListItemMinus = { link = "@markup.list.markdown" },
	MarkviewListItemStar = { link = "@markup.list.markdown" },
	MarkviewListItemPlus = { link = "@markup.list.markdown" },
	MarkviewCheckboxPending = { link = "@markup.list.unchecked.markdown" },
	MarkviewCheckboxChecked = { link = "@markup.list.checked.markdown" },
	MarkviewCheckboxUnchecked = { link = "@markup.list.unchecked.markdown" },
	MarkviewGradient0 = { ctermfg = 52 },
	MarkviewGradient1 = { ctermfg = 52 },
	MarkviewGradient2 = { ctermfg = 88 },
	MarkviewGradient3 = { ctermfg = 88 },
	MarkviewGradient4 = { ctermfg = 124 },
	MarkviewGradient5 = { ctermfg = 124 },
	MarkviewGradient6 = { ctermfg = 160 },
	MarkviewGradient7 = { ctermfg = 196 },
	MarkviewGradient8 = { ctermfg = 196 },
	MarkviewGradient9 = { ctermfg = 1 },
	MarkviewBlockQuoteSpecial = { ctermfg = 6 },
	MarkviewBlockQuoteDefault = { ctermfg = 4 },
	MarkviewBlockQuoteError = { ctermfg = 1 },
	MarkviewBlockQuoteWarn = { ctermfg = 3 },
	MarkviewBlockQuoteNote = { ctermfg = 4 },
	MarkviewBlockQuoteOk = { ctermfg = 2 },
	MarkviewPalette4Fg = { ctermfg = 6 },
}
